import type { DemoRequestConfig } from "../../features/demo-engine/config";

export const tvetRequestsDraft = [
  {
    id: "STC-CL-2026-0027",
    serviceId: "student-clearance",
    requesterId: "applicant-demo",
    assignedOfficerId: "officer-demo",
    assignedDepartmentId: "student-records",
    status: "completed",
    currentStepId: "registrar-completion",
    submittedAt: "2026-07-22T09:15:00+03:00",
    dueAt: "2026-07-25T09:15:00+03:00",
    data: {
      registrationNumber: "STC/DIT/2024/027",
      programme: "Diploma in Information Technology",
      campus: "Main Campus",
    },
  },
  {
    id: "STC-TR-2026-0156",
    serviceId: "transcript-request",
    requesterId: "applicant-demo",
    assignedOfficerId: "officer-demo",
    assignedDepartmentId: "student-records",
    status: "in-review",
    currentStepId: "registrar-approval",
    submittedAt: "2026-07-27T10:30:00+03:00",
    dueAt: "2026-08-01T10:30:00+03:00",
    data: {
      registrationNumber: "STC/DIT/2024/027",
      deliveryMethod: "Digital copy",
      paymentStatus: "Verified",
    },
  },
  {
    id: "STC-CR-2026-0155",
    serviceId: "certificate-replacement",
    requesterId: "applicant-demo",
    assignedOfficerId: "officer-demo",
    assignedDepartmentId: "student-records",
    status: "pending-approval",
    currentStepId: "registrar-approval",
    submittedAt: "2026-07-27T09:15:00+03:00",
    dueAt: "2026-08-01T09:15:00+03:00",
    data: {
      reason: "Original certificate damaged",
      identityStatus: "Verified",
      paymentStatus: "Pending",
    },
  },
  {
    id: "STC-IA-2026-0154",
    serviceId: "industrial-attachment-letter",
    requesterId: "applicant-demo",
    assignedOfficerId: "officer-admissions-demo",
    assignedDepartmentId: "career-services",
    status: "approved",
    currentStepId: "letter-generation",
    submittedAt: "2026-07-26T16:45:00+03:00",
    dueAt: "2026-07-28T16:45:00+03:00",
    data: {
      employer: "Savannah Digital Services",
      programme: "Diploma in Information Technology",
      placementStatus: "Confirmed",
    },
  },
  {
    id: "STC-CA-2026-0153",
    serviceId: "course-application",
    requesterId: "applicant-demo",
    assignedOfficerId: "officer-admissions-demo",
    assignedDepartmentId: "admissions",
    status: "in-review",
    currentStepId: "document-verification",
    submittedAt: "2026-07-26T11:20:00+03:00",
    dueAt: "2026-07-29T11:20:00+03:00",
    data: {
      programme: "Diploma in Electrical Engineering",
      intake: "September 2026",
      documentStatus: "Under review",
    },
  },
  {
    id: "STC-RG-2026-0152",
    serviceId: "class-registration",
    requesterId: "applicant-demo",
    assignedOfficerId: "officer-finance-demo",
    assignedDepartmentId: "finance",
    status: "overdue",
    currentStepId: "finance-check",
    submittedAt: "2026-07-25T14:05:00+03:00",
    dueAt: "2026-07-26T14:05:00+03:00",
    data: {
      className: "DIT 2.1",
      feeStatus: "Clarification required",
      capacityStatus: "Available",
    },
  },
] satisfies readonly DemoRequestConfig[];
