import type { DemoUserConfig } from "../../features/demo-engine/config";

export const tvetUsersDraft = [
  {
    id: "applicant-demo",
    name: "John Kamau",
    role: "applicant",
    departmentId: null,
    title: "Student Applicant",
    email: "john.kamau@example.invalid",
    telephone: "+254 711 000 027",
    active: true,
  },
  {
    id: "officer-demo",
    name: "Grace Wanjiku",
    role: "officer",
    departmentId: "student-records",
    title: "Student Records Officer",
    email: "grace.wanjiku@savannah.example",
    active: true,
  },
  {
    id: "officer-finance-demo",
    name: "Peter Mwangi",
    role: "officer",
    departmentId: "finance",
    title: "Finance Officer",
    email: "peter.mwangi@savannah.example",
    active: true,
  },
  {
    id: "officer-admissions-demo",
    name: "Amina Hassan",
    role: "officer",
    departmentId: "admissions",
    title: "Admissions Officer",
    email: "amina.hassan@savannah.example",
    active: true,
  },
  {
    id: "supervisor-demo",
    name: "Dr. Miriam Wekesa",
    role: "supervisor",
    departmentId: "registrar",
    title: "Registrar Supervisor",
    email: "miriam.wekesa@savannah.example",
    active: true,
  },
  {
    id: "admin-demo",
    name: "Jane Admin",
    role: "admin",
    departmentId: null,
    title: "Institution Administrator",
    email: "admin@savannah.example",
    active: true,
  },
] satisfies readonly DemoUserConfig[];
