import type { DemoWorkflowConfig } from "../../features/demo-engine/config";

export const tvetWorkflowsDraft = [
  {
    id: "transcript-request",
    name: "Transcript Request",
    description:
      "Academic-record review, payment verification, approval and transcript issue.",
    category: "Student Records",
    usageCount: 36,
    presentationTone: "green",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Submission",
        nextStepIds: ["document-check"],
      },
      {
        id: "document-check",
        type: "verification",
        label: "Document Check",
        departmentId: "student-records",
        slaId: "sla-transcript-request",
        nextStepIds: ["payment-check"],
      },
      {
        id: "payment-check",
        type: "verification",
        label: "Payment Check",
        departmentId: "finance",
        nextStepIds: ["records-review"],
      },
      {
        id: "records-review",
        type: "review",
        label: "Records Review",
        departmentId: "student-records",
        nextStepIds: ["registrar-approval"],
      },
      {
        id: "registrar-approval",
        type: "approval",
        label: "Registrar Approval",
        departmentId: "registrar",
        nextStepIds: ["transcript-issued"],
      },
      {
        id: "transcript-issued",
        type: "output",
        label: "Transcript Issued",
        outputLabel: "Official academic transcript",
      },
    ],
  },
  {
    id: "student-clearance",
    name: "Student Clearance",
    description:
      "Sequential and parallel clearance across institutional departments.",
    category: "Student Services",
    usageCount: 18,
    presentationTone: "green",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Submission",
        nextStepIds: ["department-clearance"],
      },
      {
        id: "department-clearance",
        type: "approval",
        label: "Department Clearance",
        departmentId: "department-office",
        slaId: "sla-student-clearance",
        nextStepIds: ["library-clearance"],
      },
      {
        id: "library-clearance",
        type: "approval",
        label: "Library Clearance",
        departmentId: "library",
        nextStepIds: ["finance-clearance"],
      },
      {
        id: "finance-clearance",
        type: "approval",
        label: "Finance Clearance",
        departmentId: "finance",
        nextStepIds: ["registrar-completion"],
      },
      {
        id: "registrar-completion",
        type: "output",
        label: "Clearance Completed",
        departmentId: "registrar",
        outputLabel: "Student clearance confirmation",
      },
    ],
  },
  {
    id: "certificate-replacement",
    name: "Certificate Replacement",
    description:
      "Identity validation, document review, approval and replacement issue.",
    category: "Academic Records",
    usageCount: 12,
    presentationTone: "purple",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Submission",
        nextStepIds: ["identity-verification"],
      },
      {
        id: "identity-verification",
        type: "verification",
        label: "Identity Verification",
        departmentId: "student-records",
        slaId: "sla-certificate-replacement",
        nextStepIds: ["supporting-document-review"],
      },
      {
        id: "supporting-document-review",
        type: "review",
        label: "Supporting Document Review",
        departmentId: "student-records",
        nextStepIds: ["finance-check"],
      },
      {
        id: "finance-check",
        type: "verification",
        label: "Replacement Fee Check",
        departmentId: "finance",
        nextStepIds: ["registrar-approval"],
      },
      {
        id: "registrar-approval",
        type: "approval",
        label: "Registrar Approval",
        departmentId: "registrar",
        nextStepIds: ["replacement-issued"],
      },
      {
        id: "replacement-issued",
        type: "output",
        label: "Replacement Issued",
        outputLabel: "Replacement certificate",
      },
    ],
  },
  {
    id: "industrial-attachment-letter",
    name: "Industrial Attachment Letter",
    description:
      "Programme validation, placement review and attachment-letter generation.",
    category: "Career Services",
    usageCount: 11,
    presentationTone: "orange",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Submission",
        nextStepIds: ["programme-validation"],
      },
      {
        id: "programme-validation",
        type: "verification",
        label: "Programme Validation",
        departmentId: "department-office",
        slaId: "sla-industrial-attachment-letter",
        nextStepIds: ["placement-review"],
      },
      {
        id: "placement-review",
        type: "review",
        label: "Placement Review",
        departmentId: "career-services",
        nextStepIds: ["hod-approval"],
      },
      {
        id: "hod-approval",
        type: "approval",
        label: "Head of Department Approval",
        departmentId: "department-office",
        nextStepIds: ["letter-generation"],
      },
      {
        id: "letter-generation",
        type: "output",
        label: "Attachment Letter Generated",
        outputLabel: "Industrial attachment letter",
      },
    ],
  },
  {
    id: "course-application",
    name: "Course Application",
    description:
      "Programme application, academic review and admission decision.",
    category: "Admissions",
    usageCount: 24,
    presentationTone: "blue",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Application Submitted",
        nextStepIds: ["document-verification"],
      },
      {
        id: "document-verification",
        type: "verification",
        label: "Document Verification",
        departmentId: "admissions",
        slaId: "sla-course-application",
        nextStepIds: ["academic-review"],
      },
      {
        id: "academic-review",
        type: "review",
        label: "Academic Review",
        departmentId: "academic-affairs",
        nextStepIds: ["admission-decision"],
      },
      {
        id: "admission-decision",
        type: "approval",
        label: "Admission Decision",
        departmentId: "admissions",
        nextStepIds: ["offer-issued"],
      },
      {
        id: "offer-issued",
        type: "output",
        label: "Offer Issued",
        outputLabel: "Admission offer letter",
      },
    ],
  },
  {
    id: "class-registration",
    name: "Class Registration",
    description:
      "Eligibility, fee-status and capacity checks before registration.",
    category: "Academic Affairs",
    usageCount: 22,
    presentationTone: "purple",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Registration Request",
        nextStepIds: ["eligibility-check"],
      },
      {
        id: "eligibility-check",
        type: "verification",
        label: "Eligibility Check",
        departmentId: "academic-affairs",
        slaId: "sla-class-registration",
        nextStepIds: ["finance-check"],
      },
      {
        id: "finance-check",
        type: "verification",
        label: "Fee Status Check",
        departmentId: "finance",
        nextStepIds: ["capacity-check"],
      },
      {
        id: "capacity-check",
        type: "decision",
        label: "Class Capacity Available?",
        departmentId: "academic-affairs",
        conditionLabel: "Available spaces are greater than zero",
        nextStepIds: ["registration-confirmed"],
      },
      {
        id: "registration-confirmed",
        type: "output",
        label: "Registration Confirmed",
        outputLabel: "Class registration confirmation",
      },
    ],
  },
  {
    id: "student-admission",
    name: "Student Admission",
    description:
      "End-to-end application, review, payment and enrolment workflow.",
    category: "Admissions",
    usageCount: 48,
    presentationTone: "blue",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Application Submitted",
        nextStepIds: ["document-verification"],
      },
      {
        id: "document-verification",
        type: "verification",
        label: "Document Verification",
        departmentId: "admissions",
        nextStepIds: ["academic-approval"],
      },
      {
        id: "academic-approval",
        type: "approval",
        label: "Academic Approval",
        departmentId: "academic-affairs",
        nextStepIds: ["fee-confirmation"],
      },
      {
        id: "fee-confirmation",
        type: "verification",
        label: "Fee Confirmation",
        departmentId: "finance",
        nextStepIds: ["admission-complete"],
      },
      {
        id: "admission-complete",
        type: "output",
        label: "Admission Completed",
        outputLabel: "Admission confirmation",
      },
    ],
  },
  {
    id: "leave-of-absence",
    name: "Leave of Absence",
    description:
      "Student request, departmental review and Registrar approval.",
    category: "Academic Affairs",
    usageCount: 29,
    presentationTone: "orange",
    status: "published",
    steps: [
      {
        id: "submission",
        type: "submission",
        label: "Leave Request Submitted",
        nextStepIds: ["department-review"],
      },
      {
        id: "department-review",
        type: "review",
        label: "Department Review",
        departmentId: "department-office",
        nextStepIds: ["registrar-approval"],
      },
      {
        id: "registrar-approval",
        type: "approval",
        label: "Registrar Approval",
        departmentId: "registrar",
        nextStepIds: ["leave-confirmation"],
      },
      {
        id: "leave-confirmation",
        type: "output",
        label: "Leave Confirmed",
        outputLabel: "Leave of absence confirmation",
      },
    ],
  },
] satisfies readonly DemoWorkflowConfig[];
